version: '3'
services:
  db:
    image: mysql:8.0.39
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myapp_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build:
      context: ./rails
    environment:
      - FIREBASE_PROJECT_ID=nput-auth
    command: bash -c "tail -f log/development.log"
    tty: true
    stdin_open: true
    volumes:
      - ./rails:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  next:
    build:
      dockerfile: ./next/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./next:/app
    ports:
      - "8000:3000"
  redis:
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mysql_data:
  redis_data: