source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# レスポンスJSONを制御する
gem "active_model_serializers"

# active_storageのバリデーション
gem "active_storage_validations"

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# 環境毎の設定管理を行う
gem "config"

# 画像ファイルをダウンロードする
gem "down"

# enum を日本語化する
gem "enum_help"

# idToken（JWT）を検証する
gem "json-jwt"

# ページネーション機能を提供する
gem "kaminari"

# MySQLに接続する
gem "mysql2", "~> 0.5"

# pumaサーバーを使えるようにする（標準gem）
gem "puma", "~> 5.0"

# cors設定を管理する
gem "rack-cors"

# rails本体（標準gem）
gem "rails", "~> 7.0.4"

# メッセージを日本語化
gem "rails-i18n"

# Redisに接続する
gem "redis"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  # N+1発生時にアラートを表示する
  gem "bullet"

  # データベースをクリーンアップする
  gem "database_cleaner-active_record"

  # 環境変数の読み込み
  gem "dotenv"

  # テスト用データを作成する
  gem "factory_bot_rails"
  gem "faker"

  # pry コンソールを使えるようにする
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # テストフレームワーク rspec を導入する
  gem "rspec-rails"

  # rubocop を使えるようにする
  gem "rubocop-rails"
  gem "rubocop-rspec"
end

group :production do
  # AWS S3に画像をアップロードする
  gem "aws-sdk-s3", require: false

  # 画像を処理する
  gem "ruby-vips"
end
